msg_separator: "\n\nã€°ï¸ã€°ï¸ã€°ï¸ã€°ï¸ã€°ï¸ã€°ï¸ã€°ï¸ã€°ï¸ã€°ï¸\n"

user_location:
  menu: "ĞœĞµĞ½Ñ"
  maps: "ĞšĞ°Ñ€Ñ‚Ğ°"
  profile: "ĞŸÑ€Ğ¾Ñ„Ğ¸Ğ»ÑŒ"

callback_char:
  cancel: "cancel"
  backpack_moving: "backpackMoving"
  goods_moving: "goodsMoving"
  eat_food: "eatFood"
  delete_item: "deleteItem"
  dress_good: "dressGood"
  take_off_good: "takeOffGood"
  change_left_hand: "changeLeftHand"
  change_right_hand: "changeRightHand"
  change_avatar: "changeAvatar"
  description: "description"
  workbench: "workbench"
  receipt: "receipt"
  put_item: "putItem"
  put_count_item: "putCountItem"
  make_new_item: "makeNewItem"
  throw_out_item: "throwOutItem"
  count_of_delete: "countOfDelete"

message:
  doing:
    up: "ğŸ”¼"
    down:  "ğŸ”½"
    left: "â—€ï¸ï¸"
    right: "â–¶ï¸"
  emoji:
    water: "\U0001F7E6"
    clock: "ğŸ•¦"
    casino: "ğŸ°"
    forbidden: "ğŸš«"
    wrench: "ğŸ”§"
    offline: "ğŸ“³"
    online: "ğŸ“´"
    stop_use: "ğŸš·"
    exclamation_mark: "â—"
    hand: "ğŸ‘‹"
    foot: "\U0001F9B6"
