msg_separator: "\n\nã€°ï¸ã€°ï¸ã€°ï¸ã€°ï¸ã€°ï¸ã€°ï¸ã€°ï¸ã€°ï¸ã€°ï¸ï¸ã€°ï¸ã€°ï¸ã€°ï¸ï¸\n"

user_location:
  menu: "ĞœĞµĞ½Ñ"
  maps: "ĞšĞ°Ñ€Ñ‚Ğ°"
  profile: "ĞŸÑ€Ğ¾Ñ„Ğ¸Ğ»ÑŒ"
  tasks_menu_message: "ğŸ“œ *ĞšĞ²ĞµÑÑ‚Ñ‹* ğŸ“Ÿ *Ğ—Ğ°Ğ´Ğ°Ğ½Ğ¸Ñ* ğŸ“† *Ğ•Ğ¶ĞµĞ´Ğ½ĞµĞ²ĞºĞ¸* ğŸ“œ"
  item_categories:
    category_title: "ğŸ• \U0001F9F1 ĞšĞ°Ñ‚ĞµĞ³Ğ¾Ñ€Ğ¸Ğ¸ ğŸŒ± ğŸ›‹"
    categories: "food resource sprout furniture other"
    other_categories: "chat"
    food: "Ğ•Ğ´Ğ° ğŸ•"
    resource: "Ğ ĞµÑÑƒÑ€ÑÑ‹ \U0001F9F1"
    sprout: "Ğ¡ĞµĞ¼ĞµĞ½Ğ° ğŸŒ±"
    furniture: "ĞœĞµĞ±ĞµĞ»ÑŒ ğŸ›‹"
    other: "Ğ’ÑÑĞºĞ¾Ğµ ğŸ§©"

callback_char:
  cancel: "cancel"
  category: "category"
  backpack_moving: "backpackMoving"
  goods_moving: "goodsMoving"
  eat_food: "eatFood"
  delete_item: "deleteItem"
  dress_good: "dressGood"
  take_off_good: "takeOffGood"
  change_left_hand: "changeLeftHand"
  change_right_hand: "changeRightHand"
  change_avatar: "changeAvatar"
  description: "description"
  workbench: "workbench"
  receipt: "receipt"
  put_item: "putItem"
  put_count_item: "putCountItem"
  make_new_item: "makeNewItem"
  throw_out_item: "throwOutItem"
  count_of_throw_out: "countOfThrowOut"
  buy_home: "buyHome"
  user_done_quest: "user_done_quest"
  user_get_quest: "user_get_quest"
  quest: "quest"
  quests: "quests"
  join_to_chat: "joinToChat"
  wordle_regulations: "wordleRegulations"

main_info:
  cost_of_house: 1000
  message_chat_is_closed: "Ğ§Ğ°Ñ‚Ğ¸Ğº Ğ¸ÑÑ‚ĞµĞº!"
  message_user_sign_in_chat: "Ğ”Ğ¾Ğ±Ñ€Ğ¾ Ğ¿Ğ¾Ğ¶Ğ°Ğ»Ğ¾Ğ²Ğ°Ñ‚ÑŒ Ğ² Ñ‡Ğ°Ñ‚Ğ¸Ğº!"

quest_statuses:
  completed: "âœ… Ğ’Ñ‹Ğ¿Ğ¾Ğ»Ğ½ĞµĞ½"
  processed: "âœ´ï¸ Ğ’ Ñ€Ğ°Ğ±Ğ¾Ñ‚Ğµ"
  new: "ğŸ†• ĞĞ¾Ğ²Ñ‹Ğ¹"
  completed_emoji: "âœ…"
  processed_emoji: "âœ´ï¸"
  new_emoji: "ğŸ†•"

elem:
  black: "â¬›"
  brown: "ğŸŸ«"
  red: "ğŸŸ¥"
  purple: "ğŸŸª"
  orange: "ğŸŸ§"
  yellow: "ğŸŸ¨"
  green: "ğŸŸ©"
  blue: "ğŸŸ¦"
  white: "â¬œ"
  door: "ğŸšª"
  day_window: "ğŸŒ ğŸ™ï¸ ğŸï¸"
  evening_window: "ğŸŒ† ğŸŒ‡ ğŸŒ„ ğŸŒ…"
  night_window: "ğŸŒƒ ğŸŒŒ ğŸŒ‰ ğŸ‘"

message:
  list_of_avatar: "ğŸ¶ ğŸ± ğŸ­ ğŸ¹ ğŸ° ğŸ¦Š ğŸ» ğŸ¼ â€ï¸ğŸ¨ ğŸ¯ ğŸ¦ ğŸ® ğŸ· ğŸ¸ ğŸµ ğŸ¦ ğŸ§ ğŸ” ğŸ¤ ğŸ¥ ğŸ¦† ğŸ´ ğŸ¦„ ğŸº ğŸ— ğŸ ğŸ¦‹ ğŸ› ğŸŒ ğŸ ğŸª² ğŸª° ğŸœ ğŸ•· ğŸª³ ğŸ¦– ğŸ¦• ğŸ™ ğŸ¦€ ğŸŸ ğŸ  ğŸ¡ ğŸ¦­"
  doing:
    up: "ğŸ”¼"
    down: "ğŸ”½"
    left: "â—€ï¸ï¸"
    right: "â–¶ï¸"
  emoji:
    water: "\U0001F7E6"
    clock: "ğŸ•¦"
    casino: "ğŸ°"
    forbidden: "ğŸš«"
    wrench: "ğŸ”§"
    offline: "ğŸ“³"
    online: "ğŸ“´"
    stop_use: "ğŸš·"
    exclamation_mark: "â—"
    hand: "ğŸ‘‹"
    foot: "\U0001F9B6"
    quest: "ğŸ“Ÿ"
    chat: "ğŸ“¨"
    wordle_game: "ğŸ”¤"
  user:
    online: "ğŸ“´ â™»ï¸ ğŸ“³"
    offline: "ğŸ“³ â™»ï¸ ğŸ“´"

errors:
  no_quest_item: "Ğ—Ğ´ĞµÑÑŒ Ğ½ĞµÑ‚ Ğ´Ğ¾ÑĞºĞ¸ Ñ ĞºĞ²ĞµÑÑ‚Ğ°Ğ¼Ğ¸!"
  user_not_has_item_in_hand: "ĞĞµĞ»ÑŒĞ·Ñ Ğ²Ğ·ÑÑ‚ÑŒ Ğ±ĞµĞ· Ğ¸Ğ½ÑÑ‚Ñ€ÑƒĞ¼ĞµĞ½Ñ‚Ğ° Ğ² Ñ€ÑƒĞºĞµ"
  user_has_other_item: "Ğ¡Ğ½Ğ°Ñ‡Ğ°Ğ»Ğ° ÑĞ½Ğ¸Ğ¼Ğ¸Ñ‚Ğµ Ğ¿Ñ€ĞµĞ´Ğ¼ĞµÑ‚, Ñ‡Ñ‚Ğ¾Ğ± Ğ½Ğ°Ğ´ĞµÑ‚ÑŒ Ğ´Ñ€ÑƒĞ³Ğ¾Ğ¹"
  user_did_not_task: "Ğ—Ğ°Ğ´Ğ°Ğ½Ğ¸Ğµ Ğ½Ğµ Ğ²Ñ‹Ğ¿Ğ¾Ğ»Ğ½ĞµĞ½Ğ¾!"
  chose_instrument_to_use: "Ğ’ Ğ·Ğ°Ğ²Ğ¸ÑĞ¸Ğ¼Ğ¾ÑÑ‚Ğ¸ Ğ¾Ñ‚ Ğ¿Ñ€ĞµĞ´Ğ¼ĞµÑ‚Ğ° Ğ² Ñ‚Ğ²Ğ¾Ğ¸Ñ… Ñ€ÑƒĞºĞ°Ñ… Ñ‚Ñ‹ Ğ¼Ğ¾Ğ¶ĞµÑˆÑŒ Ğ¿Ğ¾Ğ»ÑƒÑ‡Ğ¸Ñ‚ÑŒ Ñ€Ğ°Ğ·Ğ½Ñ‹Ğ¹ Ñ€ĞµĞ·ÑƒĞ»ÑŒÑ‚Ğ°Ñ‚. Ğ’Ñ‹Ğ±Ğ¸Ñ€Ğ°Ğ¹..."

wordle:
  text_awaiting_msg: "1 ÑĞ»Ğ¾Ğ²Ğ¾! 5 Ğ±ÑƒĞºĞ²! ĞĞµ Ğ¾ÑˆĞ¸Ğ±Ğ¸ÑÑŒ)"
  regulations: "*ĞŸĞ ĞĞ’Ğ˜Ğ›Ğ Ğ˜Ğ“Ğ Ğ«:*
\n\nã€°ï¸ã€°ï¸ã€°ï¸ã€°ï¸ã€°ï¸ã€°ï¸ã€°ï¸ã€°ï¸ã€°ï¸ï¸ã€°ï¸ã€°ï¸ã€°ï¸ï¸\n\n
Ğ£Ğ³Ğ°Ğ´Ğ°Ğ¹Ñ‚Ğµ Ğ·Ğ°Ğ³Ğ°Ğ´Ğ°Ğ½Ğ½Ğ¾Ğµ ÑĞ»Ğ¾Ğ²Ğ¾ Ğ² Ğ¸Ğ³Ñ€Ğµ *Wordle* Ñ ÑˆĞµÑÑ‚Ğ¸ Ğ¿Ğ¾Ğ¿Ñ‹Ñ‚Ğ¾Ğº. Ğ£ Ğ²ÑĞµÑ… Ğ¾Ğ´Ğ¸Ğ½Ğ°ĞºĞ¾Ğ²Ğ¾Ğµ ÑĞ»Ğ¾Ğ²Ğ¾, Ğ¿Ğ¾ÑÑ‚Ğ¾Ğ¼Ñƒ, Ğ¿Ğ¾Ğ¶Ğ°Ğ»ÑƒĞ¹ÑÑ‚Ğ°, Ğ±ĞµĞ· ÑĞ¿Ğ¾Ğ¹Ğ»ĞµÑ€Ğ¾Ğ²!
\n\n
ĞŸĞ¾ÑĞ»Ğµ ĞºĞ°Ğ¶Ğ´Ğ¾Ğ¹ Ğ¿Ğ¾Ğ¿Ñ‹Ñ‚ĞºĞ¸ Ñ†Ğ²ĞµÑ‚ Ğ±ÑƒĞºĞ² Ğ±ÑƒĞ´ĞµÑ‚ Ğ¼ĞµĞ½ÑÑ‚ÑŒÑÑ, Ñ‡Ñ‚Ğ¾Ğ±Ñ‹ Ğ¿Ğ¾ĞºĞ°Ğ·Ğ°Ñ‚ÑŒ, ĞºĞ°ĞºĞ¸Ğµ Ğ±ÑƒĞºĞ²Ñ‹ ĞµÑÑ‚ÑŒ Ğ² Ğ·Ğ°Ğ³Ğ°Ğ´Ğ°Ğ½Ğ½Ğ¾Ğ¼ ÑĞ»Ğ¾Ğ²Ğµ!
\nĞĞ°Ğ¿Ñ€Ğ¸Ğ¼ĞµÑ€, Ğ¼Ñ‹ Ğ¿Ñ‹Ñ‚Ğ°ĞµĞ¼ÑÑ Ğ¾Ñ‚Ğ³Ğ°Ğ´Ğ°Ñ‚ÑŒ ÑĞ»Ğ¾Ğ²Ğ¾ *Ğ“ĞCĞ¢Ğ¬*
\n\nã€°ï¸ã€°ï¸ã€°ï¸ã€°ï¸ã€°ï¸ã€°ï¸ã€°ï¸ã€°ï¸ã€°ï¸ï¸ã€°ï¸ã€°ï¸ã€°ï¸ï¸\n\n
ĞŸĞµÑ€Ğ²Ñ‹Ğ¼ Ğ¼Ñ‹ Ğ²Ğ²ĞµĞ»Ğ¸ ÑĞ»Ğ¾Ğ²Ğ¾ Ğ ĞµĞ±ÑƒÑ. Ğ‘ÑƒĞºĞ²Ğ° Ğ¡ ĞµÑÑ‚ÑŒ Ğ² Ğ·Ğ°Ğ³Ğ°Ğ´Ğ°Ğ½Ğ½Ğ¾Ğ¼ ÑĞ»Ğ¾Ğ²Ğµ, Ğ½Ğ¾ ÑÑ‚Ğ¾Ğ¸Ñ‚ Ğ² Ğ´Ñ€ÑƒĞ³Ğ¾Ğ¼ Ğ¼ĞµÑÑ‚Ğµ.
\n\nâ¬œï¸â¬œï¸â¬œï¸â¬œï¸ğŸŸ¨ - *Ğ Ğ•Ğ‘Ğ£Ğ¡*
\n\nã€°ï¸ã€°ï¸ã€°ï¸ã€°ï¸ã€°ï¸ã€°ï¸ã€°ï¸ã€°ï¸ã€°ï¸ï¸ã€°ï¸ã€°ï¸ã€°ï¸ï¸\n\n
Ğ—Ğ°Ñ‚ĞµĞ¼ Ğ²Ğ²ĞµĞ»Ğ¸ ÑĞ»Ğ¾Ğ²Ğ¾ _Ğ¡Ğ¾ÑĞ½Ğ°_. Ğ‘ÑƒĞºĞ²Ğ° *Ğ¡* Ğ¸ *Ğ* ĞµÑÑ‚ÑŒ Ğ² Ğ·Ğ°Ğ³Ğ°Ğ´Ğ°Ğ½Ğ½Ğ¾Ğ¼ ÑĞ»Ğ¾Ğ²Ğµ Ğ¸ ÑÑ‚Ğ¾ÑÑ‚ Ğ½Ğ° Ğ¿Ñ€Ğ°Ğ²Ğ¸Ğ»ÑŒĞ½Ñ‹Ñ… Ğ¼ĞµÑÑ‚Ğ°Ñ….
\n\nğŸŸ¨âœ…âœ…â¬œï¸â¬œï¸ - *Ğ¡ĞĞ¡ĞĞ*
\n\n_Ğ•ÑĞ»Ğ¸ Ğ±ÑƒĞºĞ²Ñ‹ Ğ½ĞµÑ‚_ Ğ² Ğ·Ğ°Ğ³Ğ°Ğ´Ğ°Ğ½Ğ½Ğ¾Ğ¼ ÑĞ»Ğ¾Ğ²Ğµ, Ñ‚Ğ¾ Ğ¾Ğ½Ğ° Ğ²Ñ‹Ğ´ĞµĞ»ÑĞµÑ‚ÑÑ _Ğ±ĞµĞ»Ñ‹Ğ¼_. 
\n\nã€°ï¸ã€°ï¸ã€°ï¸ã€°ï¸ã€°ï¸ã€°ï¸ã€°ï¸ã€°ï¸ã€°ï¸ï¸ã€°ï¸ã€°ï¸ã€°ï¸ï¸\n\n
Ğ•ÑĞ»Ğ¸ ÑĞ»Ğ¾Ğ²Ğ¾ ÑƒĞ³Ğ°Ğ´Ğ°Ğ½Ğ¾ Ğ¿Ñ€Ğ°Ğ²Ğ¸Ğ»ÑŒĞ½Ğ¾, Ñ‚Ğ¾ Ğ²ÑĞµ Ğ±ÑƒĞºĞ²Ñ‹ Ğ±ÑƒĞ´ÑƒÑ‚ Ğ²Ñ‹Ğ´ĞµĞ»ĞµĞ½Ñ‹!
\n\nâœ…âœ…âœ…âœ…âœ… - *Ğ“ĞĞ¡Ğ¢Ğ¬*
\n\nã€°ï¸ã€°ï¸ã€°ï¸ã€°ï¸ã€°ï¸ã€°ï¸ã€°ï¸ã€°ï¸ã€°ï¸ï¸ã€°ï¸ã€°ï¸ã€°ï¸ï¸\n\n
Ğ¢Ğ°ĞºĞ¶Ğµ Ğ²Ğ°Ğ¶Ğ½Ğ¾ Ğ·Ğ½Ğ°Ñ‚ÑŒ, Ñ‡Ñ‚Ğ¾ Ğ² Ğ·Ğ°Ğ³Ğ°Ğ´Ğ°Ğ½Ğ½Ğ¾Ğ¼ ÑĞ»Ğ¾Ğ²Ğµ Ğ¼Ğ¾Ğ³ÑƒÑ‚ Ğ±Ñ‹Ñ‚ÑŒ Ğ¾Ğ´Ğ¸Ğ½Ğ°ĞºĞ¾Ğ²Ñ‹Ğµ Ğ±ÑƒĞºĞ²Ñ‹. 
ĞŸĞ¾ Ğ¿Ñ€Ğ°Ğ²Ğ¸Ğ»Ğ°Ğ¼ Ñ€ÑƒÑÑĞºĞ¸Ñ… ĞºÑ€Ğ¾ÑÑĞ²Ğ¾Ñ€Ğ´Ğ¾Ğ² Ğ±ÑƒĞºĞ²Ğ° Ğ Ğ² ÑĞ»Ğ¾Ğ²Ğ°Ñ… Ğ·Ğ°Ğ¼ĞµĞ½ĞµĞ½Ğ° Ğ½Ğ° E!
\n\n
ĞšĞ°Ğ¶Ğ´Ñ‹Ğ¹ Ğ´ĞµĞ½ÑŒ Ğ·Ğ°Ğ³Ğ°Ğ´Ñ‹Ğ²Ğ°ĞµÑ‚ÑÑ Ğ½Ğ¾Ğ²Ğ¾Ğµ ÑĞ»Ğ¾Ğ²Ğ¾!
\n\n
Ğ£Ğ´Ğ°Ñ‡Ğ¸!"