msg_separator: "\n\nã€°ï¸ã€°ï¸ã€°ï¸ã€°ï¸ã€°ï¸ã€°ï¸ã€°ï¸ã€°ï¸ã€°ï¸ï¸ã€°ï¸ã€°ï¸ã€°ï¸ï¸\n"

user_location:
  menu: "ĞœĞµĞ½Ñ"
  maps: "ĞšĞ°Ñ€Ñ‚Ğ°"
  profile: "ĞŸÑ€Ğ¾Ñ„Ğ¸Ğ»ÑŒ"
  tasks_menu_message: "ğŸ“œ *ĞšĞ²ĞµÑÑ‚Ñ‹* ğŸ“Ÿ *Ğ—Ğ°Ğ´Ğ°Ğ½Ğ¸Ñ* ğŸ“† *Ğ•Ğ¶ĞµĞ´Ğ½ĞµĞ²ĞºĞ¸* ğŸ“œ"
  item_categories:
    category_title: "ğŸ• \U0001F9F1 ĞšĞ°Ñ‚ĞµĞ³Ğ¾Ñ€Ğ¸Ğ¸ ğŸŒ± ğŸ›‹"
    categories: "food resource sprout furniture other"
    other_categories: "chat"
    food: "Ğ•Ğ´Ğ° ğŸ•"
    resource: "Ğ ĞµÑÑƒÑ€ÑÑ‹ \U0001F9F1"
    sprout: "Ğ¡ĞµĞ¼ĞµĞ½Ğ° ğŸŒ±"
    furniture: "ĞœĞµĞ±ĞµĞ»ÑŒ ğŸ›‹"
    other: "Ğ’ÑÑĞºĞ¾Ğµ ğŸ§©"

callback_char:
  cancel: "cancel"
  category: "category"
  backpack_moving: "backpackMoving"
  goods_moving: "goodsMoving"
  eat_food: "eatFood"
  delete_item: "deleteItem"
  dress_good: "dressGood"
  take_off_good: "takeOffGood"
  change_left_hand: "changeLeftHand"
  change_right_hand: "changeRightHand"
  change_avatar: "changeAvatar"
  description: "description"
  workbench: "workbench"
  receipt: "receipt"
  put_item: "putItem"
  put_count_item: "putCountItem"
  make_new_item: "makeNewItem"
  throw_out_item: "throwOutItem"
  count_of_throw_out: "countOfThrowOut"
  buy_home: "buyHome"
  user_done_quest: "user_done_quest"
  user_get_quest: "user_get_quest"
  quest: "quest"
  quests: "quests"
  join_to_chat: "joinToChat"

main_info:
  cost_of_house: 1000
  message_chat_is_closed: "Ğ§Ğ°Ñ‚Ğ¸Ğº Ğ¸ÑÑ‚ĞµĞº!"
  message_user_sign_in_chat: "Ğ”Ğ¾Ğ±Ñ€Ğ¾ Ğ¿Ğ¾Ğ¶Ğ°Ğ»Ğ¾Ğ²Ğ°Ñ‚ÑŒ Ğ² Ñ‡Ğ°Ñ‚Ğ¸Ğº!"

quest_statuses:
  completed: "âœ… Ğ’Ñ‹Ğ¿Ğ¾Ğ»Ğ½ĞµĞ½"
  processed: "âœ´ï¸ Ğ’ Ñ€Ğ°Ğ±Ğ¾Ñ‚Ğµ"
  new: "ğŸ†• ĞĞ¾Ğ²Ñ‹Ğ¹"
  completed_emoji: "âœ…"
  processed_emoji: "âœ´ï¸"
  new_emoji: "ğŸ†•"

elem:
  black: "â¬›"
  brown: "ğŸŸ«"
  red: "ğŸŸ¥"
  purple: "ğŸŸª"
  orange: "ğŸŸ§"
  yellow: "ğŸŸ¨"
  green: "ğŸŸ©"
  blue: "ğŸŸ¦"
  white: "â¬œ"
  door: "ğŸšª"
  day_window: "ğŸŒ ğŸ™ï¸ ğŸï¸"
  evening_window: "ğŸŒ† ğŸŒ‡ ğŸŒ„ ğŸŒ…"
  night_window: "ğŸŒƒ ğŸŒŒ ğŸŒ‰ ğŸ‘"

message:
  list_of_avatar: "ğŸ¶ ğŸ± ğŸ­ ğŸ¹ ğŸ° ğŸ¦Š ğŸ» ğŸ¼ â€ï¸ğŸ¨ ğŸ¯ ğŸ¦ ğŸ® ğŸ· ğŸ¸ ğŸµ ğŸ¦ ğŸ§ ğŸ” ğŸ¤ ğŸ¥ ğŸ¦† ğŸ´ ğŸ¦„ ğŸº ğŸ— ğŸ ğŸ¦‹ ğŸ› ğŸŒ ğŸ ğŸª² ğŸª° ğŸœ ğŸ•· ğŸª³ ğŸ¦– ğŸ¦• ğŸ™ ğŸ¦€ ğŸŸ ğŸ  ğŸ¡ ğŸ¦­"
  doing:
    up: "ğŸ”¼"
    down: "ğŸ”½"
    left: "â—€ï¸ï¸"
    right: "â–¶ï¸"
  emoji:
    water: "\U0001F7E6"
    clock: "ğŸ•¦"
    casino: "ğŸ°"
    forbidden: "ğŸš«"
    wrench: "ğŸ”§"
    offline: "ğŸ“³"
    online: "ğŸ“´"
    stop_use: "ğŸš·"
    exclamation_mark: "â—"
    hand: "ğŸ‘‹"
    foot: "\U0001F9B6"
    quest: "ğŸ“Ÿ"
    chat: "ğŸ“¨"
  user:
    online: "ğŸ“´ â™»ï¸ ğŸ“³"
    offline: "ğŸ“³ â™»ï¸ ğŸ“´"

errors:
  no_quest_item: "Ğ—Ğ´ĞµÑÑŒ Ğ½ĞµÑ‚ Ğ´Ğ¾ÑĞºĞ¸ Ñ ĞºĞ²ĞµÑÑ‚Ğ°Ğ¼Ğ¸!"
  user_not_has_item_in_hand: "ĞĞµĞ»ÑŒĞ·Ñ Ğ²Ğ·ÑÑ‚ÑŒ Ğ±ĞµĞ· Ğ¸Ğ½ÑÑ‚Ñ€ÑƒĞ¼ĞµĞ½Ñ‚Ğ° Ğ² Ñ€ÑƒĞºĞµ"
  user_has_other_item: "Ğ¡Ğ½Ğ°Ñ‡Ğ°Ğ»Ğ° ÑĞ½Ğ¸Ğ¼Ğ¸Ñ‚Ğµ Ğ¿Ñ€ĞµĞ´Ğ¼ĞµÑ‚, Ñ‡Ñ‚Ğ¾Ğ± Ğ½Ğ°Ğ´ĞµÑ‚ÑŒ Ğ´Ñ€ÑƒĞ³Ğ¾Ğ¹"
  user_did_not_task: "Ğ—Ğ°Ğ´Ğ°Ğ½Ğ¸Ğµ Ğ½Ğµ Ğ²Ñ‹Ğ¿Ğ¾Ğ»Ğ½ĞµĞ½Ğ¾!"
  chose_instrument_to_use: "Ğ’ Ğ·Ğ°Ğ²Ğ¸ÑĞ¸Ğ¼Ğ¾ÑÑ‚Ğ¸ Ğ¾Ñ‚ Ğ¿Ñ€ĞµĞ´Ğ¼ĞµÑ‚Ğ° Ğ² Ñ‚Ğ²Ğ¾Ğ¸Ñ… Ñ€ÑƒĞºĞ°Ñ… Ñ‚Ñ‹ Ğ¼Ğ¾Ğ¶ĞµÑˆÑŒ Ğ¿Ğ¾Ğ»ÑƒÑ‡Ğ¸Ñ‚ÑŒ Ñ€Ğ°Ğ·Ğ½Ñ‹Ğ¹ Ñ€ĞµĞ·ÑƒĞ»ÑŒÑ‚Ğ°Ñ‚. Ğ’Ñ‹Ğ±Ğ¸Ñ€Ğ°Ğ¹..."